### ISSUE TITLE
This repo is too big

### ISSUE THREAD

**Issue by 0x00A** [awslabs/aws-sdk-cpp#10]
Do one thing well. Break concerns into smaller, more general purpose repos; they will be easier to reason about and test. Also, this is awesome.

**Comment by JonathanHenson** [comment]
Thank you for your comments. 

One thing I'll say. This is what we attempted to do. Each directory is, in essence, its own repo and each directory is a single concern. 

The most important directory is aws-cpp-sdk-core. This directory has everything you need to talk to an Amazon Service and nothing more. Due to the fact that that is a fairly complex task, we decided to give you some extra goodies that we created as part of that task, such as reusable crypto interfaces and reusable http clients. All of those are necessary for that task. The other directories are self-contained compilation units. Most are actual service wrappers. The rest are tests.

Currently they are all in the same base repository because that helps with versioning and our export process. Also, bringing up a new github repo everytime Amazon launches a new service is not incredibly sustainable or scalable.

We have plans to open source our generator as some of the other AWS SDKs have done and at that time, we will likely delete the actual service directories (which would greatly reduce the size of this repository). We would just include the generator at that point.

Finally, I'm glad you are excited about this project. We were hoping the community would be enthusiastic about this project. As we gather more feedback, we'll be able to make better decisions about long term direction.

I'm going to leave this open as something for us to discuss and prioritize. If you have suggestions for how exactly you would like to restructure things, we'd love to hear about it.

**Comment by bingmann** [comment]
This is very nice, but I second the request for enabling use of only a subset of the interfaces.
E.g. we would want to use the S3 interface, but don't want to compile (also, but less important: include/download) all the other ones. In the current state, we cannot use it, and will have to resort to other libraries.
Maybe just enabling a subset of libraries via the main CMake is a simple fix? I tried just including cmake subdirs, but that didnt quite work, as the main cmake does the platform tests.
Other than that, I think for including the SDK in distros, the all-in-one solution is a good idea. The distros will split them up anyway.

**Comment by JonathanHenson** [comment]
You can certainly just compile the directories you need. aws-cpp-sdk-core
and aws-cpp-sdk-s3 are all you need to compile to use s3. In that case,
just delete all add_subdirectoies but those two.

**Comment by bingmann** [comment]
Yes, but when using git submodules one doesnt really want to change the files.
for example, we include a pristine googletest via
add_subdirectory(extlib/googletest/googletest)
but that wont work with the SDK. We would have to delete the add_subdirectories (as you suggest).
Hence, a CMake variable like AWS_SDK_COMPONENTS would fix everything.

**Comment by JonathanHenson** [comment]
When we add the generator to the code base, we'll certainly have to do that
for it to work.

I like the idea of adding a bunch of cmake args to allow users to choose
their libraries as well.

Why don't you fork and do that? Then your stuff can work and I can keep you
posted as to the status of the change?

**Comment by bingmann** [comment]
Okay, will do.

**Comment by JonathanHenson** [comment]
Ok, the generator has been added to the build process and you can now build only the clients you need. See the updated readme for more info.

**Comment by skrat** [comment]
I'm trying to do this, only add the subdirectories to my cmake project, but unfortunately, you're using `CMAKE_PROJECT_NAME` throughout, which resolves to my root project name and conflicts with my target, give it a shot, make a project and try to include just S3. A sample CMake project doing just this would be appreciated.
