### ISSUE TITLE
Documented Example of Enabling Logging Does Not Work

### ISSUE THREAD

**Issue by cjhanks** [awslabs/aws-sdk-cpp#22]
```C++
// example.cpp
#include <aws/core/utils/memory/stl/AWSString.h>
#include <aws/core/utils/logging/DefaultLogSystem.h>
#include <aws/core/utils/logging/AWSLogging.h>

#include <iostream>

int main(int argc, char** argv)
{
  Aws::Utils::Logging::InitializeAWSLogging(Aws::MakeShared<Aws::Utils::Logging::DefaultLogSystem>("RunUnitTests", Aws::Utils::Logging::LogLevel::TRACE, "aws_sdk_"));
  Aws::Utils::Logging::ShutdownAWSLogging();
  return 0;
}
```

```
% g++ -std=c++11 example.cpp
example.cpp: In function ‘int main(int, char**)’:
example.cpp:10:116: error: ‘TRACE’ is not a member of ‘Aws::Utils::Logging::LogLevel’
   Aws::Utils::Logging::InitializeAWSLogging(Aws::MakeShared<Aws::Utils::Logging::DefaultLogSystem>("RunUnitTests", Aws::Utils::Logging::LogLevel::TRACE, "aws_sdk_"));
```

I have looked all through the header files for a reference to TRACE, I can't find references to it in anything but macro's.

**Comment by JonathanHenson** [comment]
Sorry, we had to change the capitalization of those enums  because of
windows and we didn't update the readme. It is Trace.

https://github.com/awslabs/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/utils/logging/LogLevel.h

// example.cpp
#include <aws/core/utils/memory/stl/AWSString.h>
#include <aws/core/utils/logging/DefaultLogSystem.h>
#include <aws/core/utils/logging/AWSLogging.h>

#include <iostream>
int main(int argc, char** argv)
{
  Aws::Utils::Logging::InitializeAWSLogging(Aws::MakeShared<Aws::Utils::Logging::DefaultLogSystem>("RunUnitTests",
Aws::Utils::Logging::LogLevel::TRACE, "aws_sdk_"));
  Aws::Utils::Logging::ShutdownAWSLogging();
  return 0;
}

% g++ -std=c++11 example.cpp
example.cpp: In function ‘int main(int, char**)’:
example.cpp:10:116: error: ‘TRACE’ is not a member of
‘Aws::Utils::Logging::LogLevel’
   Aws::Utils::Logging::InitializeAWSLogging(Aws::MakeShared<Aws::Utils::Logging::DefaultLogSystem>("RunUnitTests",
Aws::Utils::Logging::LogLevel::TRACE, "aws_sdk_"));

I have looked all through the header files for a reference to TRACE, I
can't find references to it in anything but macro's.

—
Reply to this email directly or view it on GitHub
<https://github.com/awslabs/aws-sdk-cpp/issues/22>.
